//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.BizTalk_RFC_TM_KSJD_101_BizTalkOrchestration_TM_KSJD_101Soap")]
    public interface BizTalk_RFC_TM_KSJD_101_BizTalkOrchestration_TM_KSJD_101Soap {
        
        // CODEGEN: Generating message contract since message part namespace (http://BizTalk.RFC.Schemas.OUTPUT.Z2FM_QO_FWA) does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BizTalk_RFC_TM_KSJD_101_BizTalkOrchestration_TM_KSJD_101/CALLZ" +
            "2FM_QO_FWA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Z2FM_QO_FWA_RES")]
        ConsoleApplication2.ServiceReference1.CALLZ2FM_QO_FWAResponse CALLZ2FM_QO_FWA(ConsoleApplication2.ServiceReference1.CALLZ2FM_QO_FWARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BizTalk_RFC_TM_KSJD_101_BizTalkOrchestration_TM_KSJD_101/CALLZ" +
            "2FM_QO_FWA", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication2.ServiceReference1.CALLZ2FM_QO_FWAResponse> CALLZ2FM_QO_FWAAsync(ConsoleApplication2.ServiceReference1.CALLZ2FM_QO_FWARequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.Schemas.INPUT.Z2FM_QO_FWA")]
    public partial class Z2FM_QO_FWA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mAXIMUM_ROWSField;
        
        private Z2FM_QO_FWASELECT_OPTIONS[] sELECT_OPTIONSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MAXIMUM_ROWS {
            get {
                return this.mAXIMUM_ROWSField;
            }
            set {
                this.mAXIMUM_ROWSField = value;
                this.RaisePropertyChanged("MAXIMUM_ROWS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SELECT_OPTIONS", Order=1)]
        public Z2FM_QO_FWASELECT_OPTIONS[] SELECT_OPTIONS {
            get {
                return this.sELECT_OPTIONSField;
            }
            set {
                this.sELECT_OPTIONSField = value;
                this.RaisePropertyChanged("SELECT_OPTIONS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.Schemas.INPUT.Z2FM_QO_FWA")]
    public partial class Z2FM_QO_FWASELECT_OPTIONS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aTTRIBUTE_NAMEField;
        
        private string sIGNField;
        
        private string oPTIONField;
        
        private string lOWField;
        
        private string hIGHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ATTRIBUTE_NAME {
            get {
                return this.aTTRIBUTE_NAMEField;
            }
            set {
                this.aTTRIBUTE_NAMEField = value;
                this.RaisePropertyChanged("ATTRIBUTE_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SIGN {
            get {
                return this.sIGNField;
            }
            set {
                this.sIGNField = value;
                this.RaisePropertyChanged("SIGN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OPTION {
            get {
                return this.oPTIONField;
            }
            set {
                this.oPTIONField = value;
                this.RaisePropertyChanged("OPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LOW {
            get {
                return this.lOWField;
            }
            set {
                this.lOWField = value;
                this.RaisePropertyChanged("LOW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string HIGH {
            get {
                return this.hIGHField;
            }
            set {
                this.hIGHField = value;
                this.RaisePropertyChanged("HIGH");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.Schemas.OUTPUT.Z2FM_QO_FWA")]
    public partial class Z2FM_QO_FWA_RESOUTPUT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dB_KEYField;
        
        private string fAGRMNTID044Field;
        
        private string fAGRMNTID045Field;
        
        private string mNEMONICField;
        
        private string cREATED_BYField;
        
        private string cREATED_ONField;
        
        private string cHANGED_BYField;
        
        private string cHANGED_ONField;
        
        private string fAGCATEID111Field;
        
        private string fAGTYPEID103Field;
        
        private Z2FM_QO_FWA_RESOUTPUTT_BP[] t_BPField;
        
        private Z2FM_QO_FWA_RESOUTPUTT_ORG[] t_ORGField;
        
        private Z2FM_QO_FWA_RESOUTPUTT_ITEM[] t_ITEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DB_KEY {
            get {
                return this.dB_KEYField;
            }
            set {
                this.dB_KEYField = value;
                this.RaisePropertyChanged("DB_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FAGRMNTID044 {
            get {
                return this.fAGRMNTID044Field;
            }
            set {
                this.fAGRMNTID044Field = value;
                this.RaisePropertyChanged("FAGRMNTID044");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FAGRMNTID045 {
            get {
                return this.fAGRMNTID045Field;
            }
            set {
                this.fAGRMNTID045Field = value;
                this.RaisePropertyChanged("FAGRMNTID045");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MNEMONIC {
            get {
                return this.mNEMONICField;
            }
            set {
                this.mNEMONICField = value;
                this.RaisePropertyChanged("MNEMONIC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CREATED_BY {
            get {
                return this.cREATED_BYField;
            }
            set {
                this.cREATED_BYField = value;
                this.RaisePropertyChanged("CREATED_BY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CREATED_ON {
            get {
                return this.cREATED_ONField;
            }
            set {
                this.cREATED_ONField = value;
                this.RaisePropertyChanged("CREATED_ON");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CHANGED_BY {
            get {
                return this.cHANGED_BYField;
            }
            set {
                this.cHANGED_BYField = value;
                this.RaisePropertyChanged("CHANGED_BY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CHANGED_ON {
            get {
                return this.cHANGED_ONField;
            }
            set {
                this.cHANGED_ONField = value;
                this.RaisePropertyChanged("CHANGED_ON");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string FAGCATEID111 {
            get {
                return this.fAGCATEID111Field;
            }
            set {
                this.fAGCATEID111Field = value;
                this.RaisePropertyChanged("FAGCATEID111");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string FAGTYPEID103 {
            get {
                return this.fAGTYPEID103Field;
            }
            set {
                this.fAGTYPEID103Field = value;
                this.RaisePropertyChanged("FAGTYPEID103");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("T_BP", Order=10)]
        public Z2FM_QO_FWA_RESOUTPUTT_BP[] T_BP {
            get {
                return this.t_BPField;
            }
            set {
                this.t_BPField = value;
                this.RaisePropertyChanged("T_BP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("T_ORG", Order=11)]
        public Z2FM_QO_FWA_RESOUTPUTT_ORG[] T_ORG {
            get {
                return this.t_ORGField;
            }
            set {
                this.t_ORGField = value;
                this.RaisePropertyChanged("T_ORG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("T_ITEM", Order=12)]
        public Z2FM_QO_FWA_RESOUTPUTT_ITEM[] T_ITEM {
            get {
                return this.t_ITEMField;
            }
            set {
                this.t_ITEMField = value;
                this.RaisePropertyChanged("T_ITEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.Schemas.OUTPUT.Z2FM_QO_FWA")]
    public partial class Z2FM_QO_FWA_RESOUTPUTT_BP : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dB_KEYField;
        
        private string pARENT_KEYField;
        
        private string pTY_RCO012_IField;
        
        private string pTYINTID_ID133_IField;
        
        private string uUID001Field;
        
        private string pARTY_NAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DB_KEY {
            get {
                return this.dB_KEYField;
            }
            set {
                this.dB_KEYField = value;
                this.RaisePropertyChanged("DB_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PARENT_KEY {
            get {
                return this.pARENT_KEYField;
            }
            set {
                this.pARENT_KEYField = value;
                this.RaisePropertyChanged("PARENT_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PTY_RCO012_I {
            get {
                return this.pTY_RCO012_IField;
            }
            set {
                this.pTY_RCO012_IField = value;
                this.RaisePropertyChanged("PTY_RCO012_I");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PTYINTID_ID133_I {
            get {
                return this.pTYINTID_ID133_IField;
            }
            set {
                this.pTYINTID_ID133_IField = value;
                this.RaisePropertyChanged("PTYINTID_ID133_I");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string UUID001 {
            get {
                return this.uUID001Field;
            }
            set {
                this.uUID001Field = value;
                this.RaisePropertyChanged("UUID001");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PARTY_NAME {
            get {
                return this.pARTY_NAMEField;
            }
            set {
                this.pARTY_NAMEField = value;
                this.RaisePropertyChanged("PARTY_NAME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.Schemas.OUTPUT.Z2FM_QO_FWA")]
    public partial class Z2FM_QO_FWA_RESOUTPUTT_ORG : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dB_KEYField;
        
        private string pARENT_KEYField;
        
        private string oRG_UNITField;
        
        private string oRG_EXT_IDField;
        
        private string pARTY_NAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DB_KEY {
            get {
                return this.dB_KEYField;
            }
            set {
                this.dB_KEYField = value;
                this.RaisePropertyChanged("DB_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PARENT_KEY {
            get {
                return this.pARENT_KEYField;
            }
            set {
                this.pARENT_KEYField = value;
                this.RaisePropertyChanged("PARENT_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ORG_UNIT {
            get {
                return this.oRG_UNITField;
            }
            set {
                this.oRG_UNITField = value;
                this.RaisePropertyChanged("ORG_UNIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ORG_EXT_ID {
            get {
                return this.oRG_EXT_IDField;
            }
            set {
                this.oRG_EXT_IDField = value;
                this.RaisePropertyChanged("ORG_EXT_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PARTY_NAME {
            get {
                return this.pARTY_NAMEField;
            }
            set {
                this.pARTY_NAMEField = value;
                this.RaisePropertyChanged("PARTY_NAME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.Schemas.OUTPUT.Z2FM_QO_FWA")]
    public partial class Z2FM_QO_FWA_RESOUTPUTT_ITEM : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dB_KEYField;
        
        private string pARENT_KEYField;
        
        private string iTEM_NOField;
        
        private string mNEMONICField;
        
        private string iTEM_TYPEField;
        
        private string vALIDITY_STARTField;
        
        private string vALIDITY_ENDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DB_KEY {
            get {
                return this.dB_KEYField;
            }
            set {
                this.dB_KEYField = value;
                this.RaisePropertyChanged("DB_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PARENT_KEY {
            get {
                return this.pARENT_KEYField;
            }
            set {
                this.pARENT_KEYField = value;
                this.RaisePropertyChanged("PARENT_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ITEM_NO {
            get {
                return this.iTEM_NOField;
            }
            set {
                this.iTEM_NOField = value;
                this.RaisePropertyChanged("ITEM_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MNEMONIC {
            get {
                return this.mNEMONICField;
            }
            set {
                this.mNEMONICField = value;
                this.RaisePropertyChanged("MNEMONIC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ITEM_TYPE {
            get {
                return this.iTEM_TYPEField;
            }
            set {
                this.iTEM_TYPEField = value;
                this.RaisePropertyChanged("ITEM_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string VALIDITY_START {
            get {
                return this.vALIDITY_STARTField;
            }
            set {
                this.vALIDITY_STARTField = value;
                this.RaisePropertyChanged("VALIDITY_START");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string VALIDITY_END {
            get {
                return this.vALIDITY_ENDField;
            }
            set {
                this.vALIDITY_ENDField = value;
                this.RaisePropertyChanged("VALIDITY_END");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CALLZ2FM_QO_FWA", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CALLZ2FM_QO_FWARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BizTalk.RFC.Schemas.INPUT.Z2FM_QO_FWA", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://BizTalk.RFC.Schemas.INPUT.Z2FM_QO_FWA")]
        public ConsoleApplication2.ServiceReference1.Z2FM_QO_FWA Z2FM_QO_FWA;
        
        public CALLZ2FM_QO_FWARequest() {
        }
        
        public CALLZ2FM_QO_FWARequest(ConsoleApplication2.ServiceReference1.Z2FM_QO_FWA Z2FM_QO_FWA) {
            this.Z2FM_QO_FWA = Z2FM_QO_FWA;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CALLZ2FM_QO_FWAResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CALLZ2FM_QO_FWAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BizTalk.RFC.Schemas.OUTPUT.Z2FM_QO_FWA", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://BizTalk.RFC.Schemas.OUTPUT.Z2FM_QO_FWA")]
        [System.Xml.Serialization.XmlArrayItemAttribute("OUTPUT", IsNullable=false)]
        public ConsoleApplication2.ServiceReference1.Z2FM_QO_FWA_RESOUTPUT[] Z2FM_QO_FWA_RES;
        
        public CALLZ2FM_QO_FWAResponse() {
        }
        
        public CALLZ2FM_QO_FWAResponse(ConsoleApplication2.ServiceReference1.Z2FM_QO_FWA_RESOUTPUT[] Z2FM_QO_FWA_RES) {
            this.Z2FM_QO_FWA_RES = Z2FM_QO_FWA_RES;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BizTalk_RFC_TM_KSJD_101_BizTalkOrchestration_TM_KSJD_101SoapChannel : ConsoleApplication2.ServiceReference1.BizTalk_RFC_TM_KSJD_101_BizTalkOrchestration_TM_KSJD_101Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BizTalk_RFC_TM_KSJD_101_BizTalkOrchestration_TM_KSJD_101SoapClient : System.ServiceModel.ClientBase<ConsoleApplication2.ServiceReference1.BizTalk_RFC_TM_KSJD_101_BizTalkOrchestration_TM_KSJD_101Soap>, ConsoleApplication2.ServiceReference1.BizTalk_RFC_TM_KSJD_101_BizTalkOrchestration_TM_KSJD_101Soap {
        
        public BizTalk_RFC_TM_KSJD_101_BizTalkOrchestration_TM_KSJD_101SoapClient() {
        }
        
        public BizTalk_RFC_TM_KSJD_101_BizTalkOrchestration_TM_KSJD_101SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BizTalk_RFC_TM_KSJD_101_BizTalkOrchestration_TM_KSJD_101SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizTalk_RFC_TM_KSJD_101_BizTalkOrchestration_TM_KSJD_101SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizTalk_RFC_TM_KSJD_101_BizTalkOrchestration_TM_KSJD_101SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication2.ServiceReference1.CALLZ2FM_QO_FWAResponse ConsoleApplication2.ServiceReference1.BizTalk_RFC_TM_KSJD_101_BizTalkOrchestration_TM_KSJD_101Soap.CALLZ2FM_QO_FWA(ConsoleApplication2.ServiceReference1.CALLZ2FM_QO_FWARequest request) {
            return base.Channel.CALLZ2FM_QO_FWA(request);
        }
        
        public ConsoleApplication2.ServiceReference1.Z2FM_QO_FWA_RESOUTPUT[] CALLZ2FM_QO_FWA(ConsoleApplication2.ServiceReference1.Z2FM_QO_FWA Z2FM_QO_FWA) {
            ConsoleApplication2.ServiceReference1.CALLZ2FM_QO_FWARequest inValue = new ConsoleApplication2.ServiceReference1.CALLZ2FM_QO_FWARequest();
            inValue.Z2FM_QO_FWA = Z2FM_QO_FWA;
            ConsoleApplication2.ServiceReference1.CALLZ2FM_QO_FWAResponse retVal = ((ConsoleApplication2.ServiceReference1.BizTalk_RFC_TM_KSJD_101_BizTalkOrchestration_TM_KSJD_101Soap)(this)).CALLZ2FM_QO_FWA(inValue);
            return retVal.Z2FM_QO_FWA_RES;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication2.ServiceReference1.CALLZ2FM_QO_FWAResponse> ConsoleApplication2.ServiceReference1.BizTalk_RFC_TM_KSJD_101_BizTalkOrchestration_TM_KSJD_101Soap.CALLZ2FM_QO_FWAAsync(ConsoleApplication2.ServiceReference1.CALLZ2FM_QO_FWARequest request) {
            return base.Channel.CALLZ2FM_QO_FWAAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication2.ServiceReference1.CALLZ2FM_QO_FWAResponse> CALLZ2FM_QO_FWAAsync(ConsoleApplication2.ServiceReference1.Z2FM_QO_FWA Z2FM_QO_FWA) {
            ConsoleApplication2.ServiceReference1.CALLZ2FM_QO_FWARequest inValue = new ConsoleApplication2.ServiceReference1.CALLZ2FM_QO_FWARequest();
            inValue.Z2FM_QO_FWA = Z2FM_QO_FWA;
            return ((ConsoleApplication2.ServiceReference1.BizTalk_RFC_TM_KSJD_101_BizTalkOrchestration_TM_KSJD_101Soap)(this)).CALLZ2FM_QO_FWAAsync(inValue);
        }
    }
}
