//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.BizTalk_RFC_TM_KSJD_401_Orchestration_InboundSoap")]
    public interface BizTalk_RFC_TM_KSJD_401_Orchestration_InboundSoap {
        
        // CODEGEN: Generating message contract since message part namespace (http://BizTalk.RFC.Schemas.OUTPUT.Z2FM_QO_TRQ_CRT) does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BizTalk_RFC_TM_KSJD_401_Orchestration_Inbound/Exec", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Z2FM_QO_TRQ_CRT_RES")]
        ConsoleApplication2.ServiceReference2.ExecResponse Exec(ConsoleApplication2.ServiceReference2.ExecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BizTalk_RFC_TM_KSJD_401_Orchestration_Inbound/Exec", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication2.ServiceReference2.ExecResponse> ExecAsync(ConsoleApplication2.ServiceReference2.ExecRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.Schemas.INPUT.Z2FM_QO_TRQ_CRT")]
    public partial class Z2FM_QO_TRQ_CRT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Z2FM_QO_TRQ_CRTINPUT iNPUTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Z2FM_QO_TRQ_CRTINPUT INPUT {
            get {
                return this.iNPUTField;
            }
            set {
                this.iNPUTField = value;
                this.RaisePropertyChanged("INPUT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.Schemas.INPUT.Z2FM_QO_TRQ_CRT")]
    public partial class Z2FM_QO_TRQ_CRTINPUT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Z2FM_QO_TRQ_CRTINPUTROOT rOOTField;
        
        private Z2FM_QO_TRQ_CRTINPUTZROOTEXD1 zROOTEXD1Field;
        
        private Z2FM_QO_TRQ_CRTINPUTZTD[] zTDField;
        
        private Z2FM_QO_TRQ_CRTINPUTPARTY[] pARTYField;
        
        private Z2FM_QO_TRQ_CRTINPUTITEM[] iTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Z2FM_QO_TRQ_CRTINPUTROOT ROOT {
            get {
                return this.rOOTField;
            }
            set {
                this.rOOTField = value;
                this.RaisePropertyChanged("ROOT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Z2FM_QO_TRQ_CRTINPUTZROOTEXD1 ZROOTEXD1 {
            get {
                return this.zROOTEXD1Field;
            }
            set {
                this.zROOTEXD1Field = value;
                this.RaisePropertyChanged("ZROOTEXD1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZTD", Order=2)]
        public Z2FM_QO_TRQ_CRTINPUTZTD[] ZTD {
            get {
                return this.zTDField;
            }
            set {
                this.zTDField = value;
                this.RaisePropertyChanged("ZTD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PARTY", Order=3)]
        public Z2FM_QO_TRQ_CRTINPUTPARTY[] PARTY {
            get {
                return this.pARTYField;
            }
            set {
                this.pARTYField = value;
                this.RaisePropertyChanged("PARTY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ITEM", Order=4)]
        public Z2FM_QO_TRQ_CRTINPUTITEM[] ITEM {
            get {
                return this.iTEMField;
            }
            set {
                this.iTEMField = value;
                this.RaisePropertyChanged("ITEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.Schemas.INPUT.Z2FM_QO_TRQ_CRT")]
    public partial class Z2FM_QO_TRQ_CRTINPUTROOT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aMT_GDSV_CURField;
        
        private string aMT_GDSV_VALField;
        
        private string bASE_BTD_IDField;
        
        private string cONSIGNEE_IDField;
        
        private string cONSIGNEE_KEYField;
        
        private string dES_LOC_IDField;
        
        private string dES_LOC_KEYField;
        
        private string fAG_ITEM_KEYField;
        
        private string fAG_KEYField;
        
        private string lIFECYCLEField;
        
        private string mOVEM_TYPEField;
        
        private string oRDER_PARTY_IDField;
        
        private string oRDER_PARTY_KEYField;
        
        private string pIC_EAR_REQField;
        
        private string sALES_ORG_IDField;
        
        private string sERVICE_PRODUCT_IDField;
        
        private string sHIPPER_IDField;
        
        private string sHIPPER_KEYField;
        
        private string sRC_LOC_IDField;
        
        private string sRC_LOC_KEYField;
        
        private string tRANSSRVLVL_CODEField;
        
        private string tRQ_TYPEField;
        
        private string zBCBJField;
        
        private string zCHUBCSJField;
        
        private string zCJTKField;
        
        private string zFDHField;
        
        private string zHDFYDField;
        
        private string zHWDLField;
        
        private string zHYDLField;
        
        private string zJDBZLField;
        
        private string zJHBZField;
        
        private string zJHHBRQField;
        
        private string zJHSHTHRQField;
        
        private string zJHUBCSJField;
        
        private string zJSBZLField;
        
        private string zKHFPHLField;
        
        private string zKHZBHField;
        
        private string zKJBJField;
        
        private string zMDGField;
        
        private string zQYGField;
        
        private string zSHYQBZLField;
        
        private string zTGFSField;
        
        private string zTHYQBZLField;
        
        private string zZDHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AMT_GDSV_CUR {
            get {
                return this.aMT_GDSV_CURField;
            }
            set {
                this.aMT_GDSV_CURField = value;
                this.RaisePropertyChanged("AMT_GDSV_CUR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AMT_GDSV_VAL {
            get {
                return this.aMT_GDSV_VALField;
            }
            set {
                this.aMT_GDSV_VALField = value;
                this.RaisePropertyChanged("AMT_GDSV_VAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BASE_BTD_ID {
            get {
                return this.bASE_BTD_IDField;
            }
            set {
                this.bASE_BTD_IDField = value;
                this.RaisePropertyChanged("BASE_BTD_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CONSIGNEE_ID {
            get {
                return this.cONSIGNEE_IDField;
            }
            set {
                this.cONSIGNEE_IDField = value;
                this.RaisePropertyChanged("CONSIGNEE_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CONSIGNEE_KEY {
            get {
                return this.cONSIGNEE_KEYField;
            }
            set {
                this.cONSIGNEE_KEYField = value;
                this.RaisePropertyChanged("CONSIGNEE_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DES_LOC_ID {
            get {
                return this.dES_LOC_IDField;
            }
            set {
                this.dES_LOC_IDField = value;
                this.RaisePropertyChanged("DES_LOC_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DES_LOC_KEY {
            get {
                return this.dES_LOC_KEYField;
            }
            set {
                this.dES_LOC_KEYField = value;
                this.RaisePropertyChanged("DES_LOC_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FAG_ITEM_KEY {
            get {
                return this.fAG_ITEM_KEYField;
            }
            set {
                this.fAG_ITEM_KEYField = value;
                this.RaisePropertyChanged("FAG_ITEM_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string FAG_KEY {
            get {
                return this.fAG_KEYField;
            }
            set {
                this.fAG_KEYField = value;
                this.RaisePropertyChanged("FAG_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string LIFECYCLE {
            get {
                return this.lIFECYCLEField;
            }
            set {
                this.lIFECYCLEField = value;
                this.RaisePropertyChanged("LIFECYCLE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string MOVEM_TYPE {
            get {
                return this.mOVEM_TYPEField;
            }
            set {
                this.mOVEM_TYPEField = value;
                this.RaisePropertyChanged("MOVEM_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ORDER_PARTY_ID {
            get {
                return this.oRDER_PARTY_IDField;
            }
            set {
                this.oRDER_PARTY_IDField = value;
                this.RaisePropertyChanged("ORDER_PARTY_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ORDER_PARTY_KEY {
            get {
                return this.oRDER_PARTY_KEYField;
            }
            set {
                this.oRDER_PARTY_KEYField = value;
                this.RaisePropertyChanged("ORDER_PARTY_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string PIC_EAR_REQ {
            get {
                return this.pIC_EAR_REQField;
            }
            set {
                this.pIC_EAR_REQField = value;
                this.RaisePropertyChanged("PIC_EAR_REQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string SALES_ORG_ID {
            get {
                return this.sALES_ORG_IDField;
            }
            set {
                this.sALES_ORG_IDField = value;
                this.RaisePropertyChanged("SALES_ORG_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string SERVICE_PRODUCT_ID {
            get {
                return this.sERVICE_PRODUCT_IDField;
            }
            set {
                this.sERVICE_PRODUCT_IDField = value;
                this.RaisePropertyChanged("SERVICE_PRODUCT_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string SHIPPER_ID {
            get {
                return this.sHIPPER_IDField;
            }
            set {
                this.sHIPPER_IDField = value;
                this.RaisePropertyChanged("SHIPPER_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string SHIPPER_KEY {
            get {
                return this.sHIPPER_KEYField;
            }
            set {
                this.sHIPPER_KEYField = value;
                this.RaisePropertyChanged("SHIPPER_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string SRC_LOC_ID {
            get {
                return this.sRC_LOC_IDField;
            }
            set {
                this.sRC_LOC_IDField = value;
                this.RaisePropertyChanged("SRC_LOC_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string SRC_LOC_KEY {
            get {
                return this.sRC_LOC_KEYField;
            }
            set {
                this.sRC_LOC_KEYField = value;
                this.RaisePropertyChanged("SRC_LOC_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string TRANSSRVLVL_CODE {
            get {
                return this.tRANSSRVLVL_CODEField;
            }
            set {
                this.tRANSSRVLVL_CODEField = value;
                this.RaisePropertyChanged("TRANSSRVLVL_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string TRQ_TYPE {
            get {
                return this.tRQ_TYPEField;
            }
            set {
                this.tRQ_TYPEField = value;
                this.RaisePropertyChanged("TRQ_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string ZBCBJ {
            get {
                return this.zBCBJField;
            }
            set {
                this.zBCBJField = value;
                this.RaisePropertyChanged("ZBCBJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string ZCHUBCSJ {
            get {
                return this.zCHUBCSJField;
            }
            set {
                this.zCHUBCSJField = value;
                this.RaisePropertyChanged("ZCHUBCSJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string ZCJTK {
            get {
                return this.zCJTKField;
            }
            set {
                this.zCJTKField = value;
                this.RaisePropertyChanged("ZCJTK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string ZFDH {
            get {
                return this.zFDHField;
            }
            set {
                this.zFDHField = value;
                this.RaisePropertyChanged("ZFDH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string ZHDFYD {
            get {
                return this.zHDFYDField;
            }
            set {
                this.zHDFYDField = value;
                this.RaisePropertyChanged("ZHDFYD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string ZHWDL {
            get {
                return this.zHWDLField;
            }
            set {
                this.zHWDLField = value;
                this.RaisePropertyChanged("ZHWDL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string ZHYDL {
            get {
                return this.zHYDLField;
            }
            set {
                this.zHYDLField = value;
                this.RaisePropertyChanged("ZHYDL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string ZJDBZL {
            get {
                return this.zJDBZLField;
            }
            set {
                this.zJDBZLField = value;
                this.RaisePropertyChanged("ZJDBZL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string ZJHBZ {
            get {
                return this.zJHBZField;
            }
            set {
                this.zJHBZField = value;
                this.RaisePropertyChanged("ZJHBZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string ZJHHBRQ {
            get {
                return this.zJHHBRQField;
            }
            set {
                this.zJHHBRQField = value;
                this.RaisePropertyChanged("ZJHHBRQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string ZJHSHTHRQ {
            get {
                return this.zJHSHTHRQField;
            }
            set {
                this.zJHSHTHRQField = value;
                this.RaisePropertyChanged("ZJHSHTHRQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string ZJHUBCSJ {
            get {
                return this.zJHUBCSJField;
            }
            set {
                this.zJHUBCSJField = value;
                this.RaisePropertyChanged("ZJHUBCSJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string ZJSBZL {
            get {
                return this.zJSBZLField;
            }
            set {
                this.zJSBZLField = value;
                this.RaisePropertyChanged("ZJSBZL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string ZKHFPHL {
            get {
                return this.zKHFPHLField;
            }
            set {
                this.zKHFPHLField = value;
                this.RaisePropertyChanged("ZKHFPHL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string ZKHZBH {
            get {
                return this.zKHZBHField;
            }
            set {
                this.zKHZBHField = value;
                this.RaisePropertyChanged("ZKHZBH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string ZKJBJ {
            get {
                return this.zKJBJField;
            }
            set {
                this.zKJBJField = value;
                this.RaisePropertyChanged("ZKJBJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string ZMDG {
            get {
                return this.zMDGField;
            }
            set {
                this.zMDGField = value;
                this.RaisePropertyChanged("ZMDG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string ZQYG {
            get {
                return this.zQYGField;
            }
            set {
                this.zQYGField = value;
                this.RaisePropertyChanged("ZQYG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string ZSHYQBZL {
            get {
                return this.zSHYQBZLField;
            }
            set {
                this.zSHYQBZLField = value;
                this.RaisePropertyChanged("ZSHYQBZL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string ZTGFS {
            get {
                return this.zTGFSField;
            }
            set {
                this.zTGFSField = value;
                this.RaisePropertyChanged("ZTGFS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string ZTHYQBZL {
            get {
                return this.zTHYQBZLField;
            }
            set {
                this.zTHYQBZLField = value;
                this.RaisePropertyChanged("ZTHYQBZL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string ZZDH {
            get {
                return this.zZDHField;
            }
            set {
                this.zZDHField = value;
                this.RaisePropertyChanged("ZZDH");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.Schemas.INPUT.Z2FM_QO_TRQ_CRT")]
    public partial class Z2FM_QO_TRQ_CRTINPUTZROOTEXD1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zCGSField;
        
        private string zCGSJSHField;
        
        private string zCZTG1Field;
        
        private string zDCYQBZLField;
        
        private string zJHField;
        
        private string zJHSHRQField;
        
        private string zJHTHRQZGRQField;
        
        private string zKHFPHField;
        
        private string zKHJSHField;
        
        private string zKHRQField;
        
        private string zKHSXField;
        
        private string zLHField;
        
        private string zLXField;
        
        private string zMDG1HCField;
        
        private string zMDGHCField;
        
        private string zMDHJField;
        
        private string zPCFSField;
        
        private string zQTBZLField;
        
        private string zQYDHCField;
        
        private string zQYGField;
        
        private string zQYG1Field;
        
        private string zTDMDGHCField;
        
        private string zTYHBJField;
        
        private string zXSYField;
        
        private string zYCCMHJField;
        
        private string zYCHCHJField;
        
        private string zYCTDHJField;
        
        private string zZLQQField;
        
        private string zZLQQRQField;
        
        private string zZYGQHCField;
        
        private string zZZGHCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ZCGS {
            get {
                return this.zCGSField;
            }
            set {
                this.zCGSField = value;
                this.RaisePropertyChanged("ZCGS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ZCGSJSH {
            get {
                return this.zCGSJSHField;
            }
            set {
                this.zCGSJSHField = value;
                this.RaisePropertyChanged("ZCGSJSH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ZCZTG1 {
            get {
                return this.zCZTG1Field;
            }
            set {
                this.zCZTG1Field = value;
                this.RaisePropertyChanged("ZCZTG1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ZDCYQBZL {
            get {
                return this.zDCYQBZLField;
            }
            set {
                this.zDCYQBZLField = value;
                this.RaisePropertyChanged("ZDCYQBZL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ZJH {
            get {
                return this.zJHField;
            }
            set {
                this.zJHField = value;
                this.RaisePropertyChanged("ZJH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ZJHSHRQ {
            get {
                return this.zJHSHRQField;
            }
            set {
                this.zJHSHRQField = value;
                this.RaisePropertyChanged("ZJHSHRQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ZJHTHRQZGRQ {
            get {
                return this.zJHTHRQZGRQField;
            }
            set {
                this.zJHTHRQZGRQField = value;
                this.RaisePropertyChanged("ZJHTHRQZGRQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ZKHFPH {
            get {
                return this.zKHFPHField;
            }
            set {
                this.zKHFPHField = value;
                this.RaisePropertyChanged("ZKHFPH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ZKHJSH {
            get {
                return this.zKHJSHField;
            }
            set {
                this.zKHJSHField = value;
                this.RaisePropertyChanged("ZKHJSH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ZKHRQ {
            get {
                return this.zKHRQField;
            }
            set {
                this.zKHRQField = value;
                this.RaisePropertyChanged("ZKHRQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ZKHSX {
            get {
                return this.zKHSXField;
            }
            set {
                this.zKHSXField = value;
                this.RaisePropertyChanged("ZKHSX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ZLH {
            get {
                return this.zLHField;
            }
            set {
                this.zLHField = value;
                this.RaisePropertyChanged("ZLH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ZLX {
            get {
                return this.zLXField;
            }
            set {
                this.zLXField = value;
                this.RaisePropertyChanged("ZLX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ZMDG1HC {
            get {
                return this.zMDG1HCField;
            }
            set {
                this.zMDG1HCField = value;
                this.RaisePropertyChanged("ZMDG1HC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ZMDGHC {
            get {
                return this.zMDGHCField;
            }
            set {
                this.zMDGHCField = value;
                this.RaisePropertyChanged("ZMDGHC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ZMDHJ {
            get {
                return this.zMDHJField;
            }
            set {
                this.zMDHJField = value;
                this.RaisePropertyChanged("ZMDHJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ZPCFS {
            get {
                return this.zPCFSField;
            }
            set {
                this.zPCFSField = value;
                this.RaisePropertyChanged("ZPCFS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string ZQTBZL {
            get {
                return this.zQTBZLField;
            }
            set {
                this.zQTBZLField = value;
                this.RaisePropertyChanged("ZQTBZL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ZQYDHC {
            get {
                return this.zQYDHCField;
            }
            set {
                this.zQYDHCField = value;
                this.RaisePropertyChanged("ZQYDHC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string ZQYG {
            get {
                return this.zQYGField;
            }
            set {
                this.zQYGField = value;
                this.RaisePropertyChanged("ZQYG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string ZQYG1 {
            get {
                return this.zQYG1Field;
            }
            set {
                this.zQYG1Field = value;
                this.RaisePropertyChanged("ZQYG1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string ZTDMDGHC {
            get {
                return this.zTDMDGHCField;
            }
            set {
                this.zTDMDGHCField = value;
                this.RaisePropertyChanged("ZTDMDGHC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string ZTYHBJ {
            get {
                return this.zTYHBJField;
            }
            set {
                this.zTYHBJField = value;
                this.RaisePropertyChanged("ZTYHBJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string ZXSY {
            get {
                return this.zXSYField;
            }
            set {
                this.zXSYField = value;
                this.RaisePropertyChanged("ZXSY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string ZYCCMHJ {
            get {
                return this.zYCCMHJField;
            }
            set {
                this.zYCCMHJField = value;
                this.RaisePropertyChanged("ZYCCMHJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string ZYCHCHJ {
            get {
                return this.zYCHCHJField;
            }
            set {
                this.zYCHCHJField = value;
                this.RaisePropertyChanged("ZYCHCHJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string ZYCTDHJ {
            get {
                return this.zYCTDHJField;
            }
            set {
                this.zYCTDHJField = value;
                this.RaisePropertyChanged("ZYCTDHJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string ZZLQQ {
            get {
                return this.zZLQQField;
            }
            set {
                this.zZLQQField = value;
                this.RaisePropertyChanged("ZZLQQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string ZZLQQRQ {
            get {
                return this.zZLQQRQField;
            }
            set {
                this.zZLQQRQField = value;
                this.RaisePropertyChanged("ZZLQQRQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string ZZYGQHC {
            get {
                return this.zZYGQHCField;
            }
            set {
                this.zZYGQHCField = value;
                this.RaisePropertyChanged("ZZYGQHC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string ZZZGHC {
            get {
                return this.zZZGHCField;
            }
            set {
                this.zZZGHCField = value;
                this.RaisePropertyChanged("ZZZGHC");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.Schemas.INPUT.Z2FM_QO_TRQ_CRT")]
    public partial class Z2FM_QO_TRQ_CRTINPUTZTD : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zBGKZXField;
        
        private string zDRTZRField;
        
        private string zDRTZRJCField;
        
        private string zFHRField;
        
        private string zFHRJCField;
        
        private string zHWMSField;
        
        private string zKHZBHField;
        
        private string zMTField;
        
        private string zSBYTDField;
        
        private string zSHRField;
        
        private string zSHRJCField;
        
        private string zTZRField;
        
        private string zTZRJCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ZBGKZX {
            get {
                return this.zBGKZXField;
            }
            set {
                this.zBGKZXField = value;
                this.RaisePropertyChanged("ZBGKZX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ZDRTZR {
            get {
                return this.zDRTZRField;
            }
            set {
                this.zDRTZRField = value;
                this.RaisePropertyChanged("ZDRTZR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ZDRTZRJC {
            get {
                return this.zDRTZRJCField;
            }
            set {
                this.zDRTZRJCField = value;
                this.RaisePropertyChanged("ZDRTZRJC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ZFHR {
            get {
                return this.zFHRField;
            }
            set {
                this.zFHRField = value;
                this.RaisePropertyChanged("ZFHR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ZFHRJC {
            get {
                return this.zFHRJCField;
            }
            set {
                this.zFHRJCField = value;
                this.RaisePropertyChanged("ZFHRJC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ZHWMS {
            get {
                return this.zHWMSField;
            }
            set {
                this.zHWMSField = value;
                this.RaisePropertyChanged("ZHWMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ZKHZBH {
            get {
                return this.zKHZBHField;
            }
            set {
                this.zKHZBHField = value;
                this.RaisePropertyChanged("ZKHZBH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ZMT {
            get {
                return this.zMTField;
            }
            set {
                this.zMTField = value;
                this.RaisePropertyChanged("ZMT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ZSBYTD {
            get {
                return this.zSBYTDField;
            }
            set {
                this.zSBYTDField = value;
                this.RaisePropertyChanged("ZSBYTD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ZSHR {
            get {
                return this.zSHRField;
            }
            set {
                this.zSHRField = value;
                this.RaisePropertyChanged("ZSHR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ZSHRJC {
            get {
                return this.zSHRJCField;
            }
            set {
                this.zSHRJCField = value;
                this.RaisePropertyChanged("ZSHRJC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ZTZR {
            get {
                return this.zTZRField;
            }
            set {
                this.zTZRField = value;
                this.RaisePropertyChanged("ZTZR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ZTZRJC {
            get {
                return this.zTZRJCField;
            }
            set {
                this.zTZRJCField = value;
                this.RaisePropertyChanged("ZTZRJC");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.Schemas.INPUT.Z2FM_QO_TRQ_CRT")]
    public partial class Z2FM_QO_TRQ_CRTINPUTPARTY : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pARTY_IDField;
        
        private string pARTY_RCOField;
        
        private string pARTY_UUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PARTY_ID {
            get {
                return this.pARTY_IDField;
            }
            set {
                this.pARTY_IDField = value;
                this.RaisePropertyChanged("PARTY_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PARTY_RCO {
            get {
                return this.pARTY_RCOField;
            }
            set {
                this.pARTY_RCOField = value;
                this.RaisePropertyChanged("PARTY_RCO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PARTY_UUID {
            get {
                return this.pARTY_UUIDField;
            }
            set {
                this.pARTY_UUIDField = value;
                this.RaisePropertyChanged("PARTY_UUID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.Schemas.INPUT.Z2FM_QO_TRQ_CRT")]
    public partial class Z2FM_QO_TRQ_CRTINPUTITEM : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Z2FM_QO_TRQ_CRTINPUTITEMITEM iTEMField;
        
        private Z2FM_QO_TRQ_CRTINPUTITEMZITEMEXD1 zITEMEXD1Field;
        
        private Z2FM_QO_TRQ_CRTINPUTITEMITEMCCODE iTEMCCODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Z2FM_QO_TRQ_CRTINPUTITEMITEM ITEM {
            get {
                return this.iTEMField;
            }
            set {
                this.iTEMField = value;
                this.RaisePropertyChanged("ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Z2FM_QO_TRQ_CRTINPUTITEMZITEMEXD1 ZITEMEXD1 {
            get {
                return this.zITEMEXD1Field;
            }
            set {
                this.zITEMEXD1Field = value;
                this.RaisePropertyChanged("ZITEMEXD1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Z2FM_QO_TRQ_CRTINPUTITEMITEMCCODE ITEMCCODE {
            get {
                return this.iTEMCCODEField;
            }
            set {
                this.iTEMCCODEField = value;
                this.RaisePropertyChanged("ITEMCCODE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.Schemas.INPUT.Z2FM_QO_TRQ_CRT")]
    public partial class Z2FM_QO_TRQ_CRTINPUTITEMITEM : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iTEM_IDField;
        
        private string iTEM_CATField;
        
        private string tRANSSRVREQ_CODEField;
        
        private string qUA_PCS_VALField;
        
        private string qUA_PCS_UNIField;
        
        private string bASE_UOM_VALField;
        
        private string bASE_UOM_UNIField;
        
        private string gRO_WEI_VALField;
        
        private string gRO_WEI_UNIField;
        
        private string gRO_VOL_VALField;
        
        private string gRO_VOL_UNIField;
        
        private string pACKAGE_TCOField;
        
        private string zGQSXField;
        
        private string zJCKKAField;
        
        private string zKACZRQHJField;
        
        private string zMYFS1Field;
        
        private string zSBFSField;
        
        private string zSBGQField;
        
        private string zWTFSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ITEM_ID {
            get {
                return this.iTEM_IDField;
            }
            set {
                this.iTEM_IDField = value;
                this.RaisePropertyChanged("ITEM_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ITEM_CAT {
            get {
                return this.iTEM_CATField;
            }
            set {
                this.iTEM_CATField = value;
                this.RaisePropertyChanged("ITEM_CAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TRANSSRVREQ_CODE {
            get {
                return this.tRANSSRVREQ_CODEField;
            }
            set {
                this.tRANSSRVREQ_CODEField = value;
                this.RaisePropertyChanged("TRANSSRVREQ_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string QUA_PCS_VAL {
            get {
                return this.qUA_PCS_VALField;
            }
            set {
                this.qUA_PCS_VALField = value;
                this.RaisePropertyChanged("QUA_PCS_VAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string QUA_PCS_UNI {
            get {
                return this.qUA_PCS_UNIField;
            }
            set {
                this.qUA_PCS_UNIField = value;
                this.RaisePropertyChanged("QUA_PCS_UNI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BASE_UOM_VAL {
            get {
                return this.bASE_UOM_VALField;
            }
            set {
                this.bASE_UOM_VALField = value;
                this.RaisePropertyChanged("BASE_UOM_VAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string BASE_UOM_UNI {
            get {
                return this.bASE_UOM_UNIField;
            }
            set {
                this.bASE_UOM_UNIField = value;
                this.RaisePropertyChanged("BASE_UOM_UNI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string GRO_WEI_VAL {
            get {
                return this.gRO_WEI_VALField;
            }
            set {
                this.gRO_WEI_VALField = value;
                this.RaisePropertyChanged("GRO_WEI_VAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string GRO_WEI_UNI {
            get {
                return this.gRO_WEI_UNIField;
            }
            set {
                this.gRO_WEI_UNIField = value;
                this.RaisePropertyChanged("GRO_WEI_UNI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string GRO_VOL_VAL {
            get {
                return this.gRO_VOL_VALField;
            }
            set {
                this.gRO_VOL_VALField = value;
                this.RaisePropertyChanged("GRO_VOL_VAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string GRO_VOL_UNI {
            get {
                return this.gRO_VOL_UNIField;
            }
            set {
                this.gRO_VOL_UNIField = value;
                this.RaisePropertyChanged("GRO_VOL_UNI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string PACKAGE_TCO {
            get {
                return this.pACKAGE_TCOField;
            }
            set {
                this.pACKAGE_TCOField = value;
                this.RaisePropertyChanged("PACKAGE_TCO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ZGQSX {
            get {
                return this.zGQSXField;
            }
            set {
                this.zGQSXField = value;
                this.RaisePropertyChanged("ZGQSX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ZJCKKA {
            get {
                return this.zJCKKAField;
            }
            set {
                this.zJCKKAField = value;
                this.RaisePropertyChanged("ZJCKKA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ZKACZRQHJ {
            get {
                return this.zKACZRQHJField;
            }
            set {
                this.zKACZRQHJField = value;
                this.RaisePropertyChanged("ZKACZRQHJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ZMYFS1 {
            get {
                return this.zMYFS1Field;
            }
            set {
                this.zMYFS1Field = value;
                this.RaisePropertyChanged("ZMYFS1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ZSBFS {
            get {
                return this.zSBFSField;
            }
            set {
                this.zSBFSField = value;
                this.RaisePropertyChanged("ZSBFS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string ZSBGQ {
            get {
                return this.zSBGQField;
            }
            set {
                this.zSBGQField = value;
                this.RaisePropertyChanged("ZSBGQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ZWTFS {
            get {
                return this.zWTFSField;
            }
            set {
                this.zWTFSField = value;
                this.RaisePropertyChanged("ZWTFS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.Schemas.INPUT.Z2FM_QO_TRQ_CRT")]
    public partial class Z2FM_QO_TRQ_CRTINPUTITEMZITEMEXD1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zBGFSField;
        
        private string zBGJYDWField;
        
        private string zCGZZDMField;
        
        private string zEXZYHTFPHField;
        
        private string zFWGFDM1Field;
        
        private string zJHBGRQField;
        
        private string zMZBZField;
        
        private string zZHQDHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ZBGFS {
            get {
                return this.zBGFSField;
            }
            set {
                this.zBGFSField = value;
                this.RaisePropertyChanged("ZBGFS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ZBGJYDW {
            get {
                return this.zBGJYDWField;
            }
            set {
                this.zBGJYDWField = value;
                this.RaisePropertyChanged("ZBGJYDW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ZCGZZDM {
            get {
                return this.zCGZZDMField;
            }
            set {
                this.zCGZZDMField = value;
                this.RaisePropertyChanged("ZCGZZDM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ZEXZYHTFPH {
            get {
                return this.zEXZYHTFPHField;
            }
            set {
                this.zEXZYHTFPHField = value;
                this.RaisePropertyChanged("ZEXZYHTFPH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ZFWGFDM1 {
            get {
                return this.zFWGFDM1Field;
            }
            set {
                this.zFWGFDM1Field = value;
                this.RaisePropertyChanged("ZFWGFDM1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ZJHBGRQ {
            get {
                return this.zJHBGRQField;
            }
            set {
                this.zJHBGRQField = value;
                this.RaisePropertyChanged("ZJHBGRQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ZMZBZ {
            get {
                return this.zMZBZField;
            }
            set {
                this.zMZBZField = value;
                this.RaisePropertyChanged("ZMZBZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ZZHQDH {
            get {
                return this.zZHQDHField;
            }
            set {
                this.zZHQDHField = value;
                this.RaisePropertyChanged("ZZHQDH");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.Schemas.INPUT.Z2FM_QO_TRQ_CRT")]
    public partial class Z2FM_QO_TRQ_CRTINPUTITEMITEMCCODE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cCODE_TYPEField;
        
        private string cCODEField;
        
        private string zZWPMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CCODE_TYPE {
            get {
                return this.cCODE_TYPEField;
            }
            set {
                this.cCODE_TYPEField = value;
                this.RaisePropertyChanged("CCODE_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CCODE {
            get {
                return this.cCODEField;
            }
            set {
                this.cCODEField = value;
                this.RaisePropertyChanged("CCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ZZWPM {
            get {
                return this.zZWPMField;
            }
            set {
                this.zZWPMField = value;
                this.RaisePropertyChanged("ZZWPM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.Schemas.OUTPUT.Z2FM_QO_TRQ_CRT")]
    public partial class Z2FM_QO_TRQ_CRT_RES : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Z2FM_QO_TRQ_CRT_RESOUTPUT oUTPUTField;
        
        private Z2FM_QO_TRQ_CRT_RESET_RETURN[] eT_RETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Z2FM_QO_TRQ_CRT_RESOUTPUT OUTPUT {
            get {
                return this.oUTPUTField;
            }
            set {
                this.oUTPUTField = value;
                this.RaisePropertyChanged("OUTPUT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ET_RETURN", Order=1)]
        public Z2FM_QO_TRQ_CRT_RESET_RETURN[] ET_RETURN {
            get {
                return this.eT_RETURNField;
            }
            set {
                this.eT_RETURNField = value;
                this.RaisePropertyChanged("ET_RETURN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.Schemas.OUTPUT.Z2FM_QO_TRQ_CRT")]
    public partial class Z2FM_QO_TRQ_CRT_RESOUTPUT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mANDTField;
        
        private string dB_KEYField;
        
        private string tRQ_IDField;
        
        private string tRQ_TYPEField;
        
        private string oRDER_DATEField;
        
        private string cREATED_BYField;
        
        private string sALES_ORG_IDField;
        
        private Z2FM_QO_TRQ_CRT_RESOUTPUTITEM[] iTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MANDT {
            get {
                return this.mANDTField;
            }
            set {
                this.mANDTField = value;
                this.RaisePropertyChanged("MANDT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DB_KEY {
            get {
                return this.dB_KEYField;
            }
            set {
                this.dB_KEYField = value;
                this.RaisePropertyChanged("DB_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TRQ_ID {
            get {
                return this.tRQ_IDField;
            }
            set {
                this.tRQ_IDField = value;
                this.RaisePropertyChanged("TRQ_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TRQ_TYPE {
            get {
                return this.tRQ_TYPEField;
            }
            set {
                this.tRQ_TYPEField = value;
                this.RaisePropertyChanged("TRQ_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ORDER_DATE {
            get {
                return this.oRDER_DATEField;
            }
            set {
                this.oRDER_DATEField = value;
                this.RaisePropertyChanged("ORDER_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CREATED_BY {
            get {
                return this.cREATED_BYField;
            }
            set {
                this.cREATED_BYField = value;
                this.RaisePropertyChanged("CREATED_BY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SALES_ORG_ID {
            get {
                return this.sALES_ORG_IDField;
            }
            set {
                this.sALES_ORG_IDField = value;
                this.RaisePropertyChanged("SALES_ORG_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ITEM", Order=7)]
        public Z2FM_QO_TRQ_CRT_RESOUTPUTITEM[] ITEM {
            get {
                return this.iTEMField;
            }
            set {
                this.iTEMField = value;
                this.RaisePropertyChanged("ITEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.Schemas.OUTPUT.Z2FM_QO_TRQ_CRT")]
    public partial class Z2FM_QO_TRQ_CRT_RESOUTPUTITEM : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mANDTField;
        
        private string dB_KEYField;
        
        private string pARENT_KEYField;
        
        private string iTEM_IDField;
        
        private string iTEM_CATField;
        
        private string tRANSSRVREQ_CODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MANDT {
            get {
                return this.mANDTField;
            }
            set {
                this.mANDTField = value;
                this.RaisePropertyChanged("MANDT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DB_KEY {
            get {
                return this.dB_KEYField;
            }
            set {
                this.dB_KEYField = value;
                this.RaisePropertyChanged("DB_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PARENT_KEY {
            get {
                return this.pARENT_KEYField;
            }
            set {
                this.pARENT_KEYField = value;
                this.RaisePropertyChanged("PARENT_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ITEM_ID {
            get {
                return this.iTEM_IDField;
            }
            set {
                this.iTEM_IDField = value;
                this.RaisePropertyChanged("ITEM_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ITEM_CAT {
            get {
                return this.iTEM_CATField;
            }
            set {
                this.iTEM_CATField = value;
                this.RaisePropertyChanged("ITEM_CAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TRANSSRVREQ_CODE {
            get {
                return this.tRANSSRVREQ_CODEField;
            }
            set {
                this.tRANSSRVREQ_CODEField = value;
                this.RaisePropertyChanged("TRANSSRVREQ_CODE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.Schemas.OUTPUT.Z2FM_QO_TRQ_CRT")]
    public partial class Z2FM_QO_TRQ_CRT_RESET_RETURN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mSG_TYPEField;
        
        private string mSG_IDField;
        
        private string mSG_NOField;
        
        private string mSG_TEXTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MSG_TYPE {
            get {
                return this.mSG_TYPEField;
            }
            set {
                this.mSG_TYPEField = value;
                this.RaisePropertyChanged("MSG_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MSG_ID {
            get {
                return this.mSG_IDField;
            }
            set {
                this.mSG_IDField = value;
                this.RaisePropertyChanged("MSG_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MSG_NO {
            get {
                return this.mSG_NOField;
            }
            set {
                this.mSG_NOField = value;
                this.RaisePropertyChanged("MSG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MSG_TEXT {
            get {
                return this.mSG_TEXTField;
            }
            set {
                this.mSG_TEXTField = value;
                this.RaisePropertyChanged("MSG_TEXT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Exec", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BizTalk.RFC.Schemas.INPUT.Z2FM_QO_TRQ_CRT", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://BizTalk.RFC.Schemas.INPUT.Z2FM_QO_TRQ_CRT")]
        public ConsoleApplication2.ServiceReference2.Z2FM_QO_TRQ_CRT Z2FM_QO_TRQ_CRT;
        
        public ExecRequest() {
        }
        
        public ExecRequest(ConsoleApplication2.ServiceReference2.Z2FM_QO_TRQ_CRT Z2FM_QO_TRQ_CRT) {
            this.Z2FM_QO_TRQ_CRT = Z2FM_QO_TRQ_CRT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BizTalk.RFC.Schemas.OUTPUT.Z2FM_QO_TRQ_CRT", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://BizTalk.RFC.Schemas.OUTPUT.Z2FM_QO_TRQ_CRT")]
        public ConsoleApplication2.ServiceReference2.Z2FM_QO_TRQ_CRT_RES Z2FM_QO_TRQ_CRT_RES;
        
        public ExecResponse() {
        }
        
        public ExecResponse(ConsoleApplication2.ServiceReference2.Z2FM_QO_TRQ_CRT_RES Z2FM_QO_TRQ_CRT_RES) {
            this.Z2FM_QO_TRQ_CRT_RES = Z2FM_QO_TRQ_CRT_RES;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BizTalk_RFC_TM_KSJD_401_Orchestration_InboundSoapChannel : ConsoleApplication2.ServiceReference2.BizTalk_RFC_TM_KSJD_401_Orchestration_InboundSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BizTalk_RFC_TM_KSJD_401_Orchestration_InboundSoapClient : System.ServiceModel.ClientBase<ConsoleApplication2.ServiceReference2.BizTalk_RFC_TM_KSJD_401_Orchestration_InboundSoap>, ConsoleApplication2.ServiceReference2.BizTalk_RFC_TM_KSJD_401_Orchestration_InboundSoap {
        
        public BizTalk_RFC_TM_KSJD_401_Orchestration_InboundSoapClient() {
        }
        
        public BizTalk_RFC_TM_KSJD_401_Orchestration_InboundSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BizTalk_RFC_TM_KSJD_401_Orchestration_InboundSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizTalk_RFC_TM_KSJD_401_Orchestration_InboundSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizTalk_RFC_TM_KSJD_401_Orchestration_InboundSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication2.ServiceReference2.ExecResponse ConsoleApplication2.ServiceReference2.BizTalk_RFC_TM_KSJD_401_Orchestration_InboundSoap.Exec(ConsoleApplication2.ServiceReference2.ExecRequest request) {
            return base.Channel.Exec(request);
        }
        
        public ConsoleApplication2.ServiceReference2.Z2FM_QO_TRQ_CRT_RES Exec(ConsoleApplication2.ServiceReference2.Z2FM_QO_TRQ_CRT Z2FM_QO_TRQ_CRT) {
            ConsoleApplication2.ServiceReference2.ExecRequest inValue = new ConsoleApplication2.ServiceReference2.ExecRequest();
            inValue.Z2FM_QO_TRQ_CRT = Z2FM_QO_TRQ_CRT;
            ConsoleApplication2.ServiceReference2.ExecResponse retVal = ((ConsoleApplication2.ServiceReference2.BizTalk_RFC_TM_KSJD_401_Orchestration_InboundSoap)(this)).Exec(inValue);
            return retVal.Z2FM_QO_TRQ_CRT_RES;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication2.ServiceReference2.ExecResponse> ConsoleApplication2.ServiceReference2.BizTalk_RFC_TM_KSJD_401_Orchestration_InboundSoap.ExecAsync(ConsoleApplication2.ServiceReference2.ExecRequest request) {
            return base.Channel.ExecAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication2.ServiceReference2.ExecResponse> ExecAsync(ConsoleApplication2.ServiceReference2.Z2FM_QO_TRQ_CRT Z2FM_QO_TRQ_CRT) {
            ConsoleApplication2.ServiceReference2.ExecRequest inValue = new ConsoleApplication2.ServiceReference2.ExecRequest();
            inValue.Z2FM_QO_TRQ_CRT = Z2FM_QO_TRQ_CRT;
            return ((ConsoleApplication2.ServiceReference2.BizTalk_RFC_TM_KSJD_401_Orchestration_InboundSoap)(this)).ExecAsync(inValue);
        }
    }
}
